package com.edibca.oftalmoallergan;

/**
 * Created by USER on 30/09/2015.
 */
public class Masinfo {
    private String sec_1_a="Los ojos son órganos que refractan y enfocan la luz hacia los fotorreceptores situados en la parte posterior de cada uno. Cada ojo se localiza en una depresión ósea en el cráneo llamada órbita, cuyas paredes están conformadas por varios huesos diferentes.<sup>1</sup><br /><br /><ul><li>Las <strong>cejas</strong> protegen al globo ocular del sol y posibles partículas contaminantes. Las pestañas contribuyen a esta función.<sup>1</sup></li><br /><li>Los <strong>párpados</strong> contienen músculos que ayudan a cerrar el ojo para protegerlo de la resequedad a través del parpadeo, que ocurre cada 7 segundos aproximadamente.<sup>1</sup></li><br /><li>La <strong>fisura palpebral</strong> es el espacio comprendido entre el párpado superior e inferior. Las comisuras (medial y lateral) son los ángulos en donde los párpados se juntan. En la comisura medial se localiza la carúncula lacrimal, que contiene glándulas secretoras.<sup>1</sup></li></ul>";
    private String sec_1_b="El ojo posee básicamente tres túnicas o capas:<br /><br /><ol><li><strong>La túnica fibrosa.</strong> Situada en la parte externa del globo ocular, se compone de la parte blanca llamada esclera (que protege las estructuras internas) y la córnea (membrana convexa transparente) que refracta y enfoca los rayos de luz.<sup>1</sup></li><br /><li><strong>La túnica vascular (úvea).</strong> Compuesta por la membrana coroides (que oscurece el interior del ojo), el cuerpo ciliar (un sistema complejo de músculos y fibras que ayudan a enfocar la luz) y el iris (quien da el color de los ojos y está constituido por fibras musculares que ayudan a regular la cantidad de luz que entra al ojo a través de la pupila).<sup>1</sup> El cristalino es el segundo lente del ojo, y está suspendido del cuerpo ciliar a través de la zónula (ligamentos suspensorios en el esquema). Este lente es flexible cuando somos jóvenes y nos permite enfocar de lejos y de cerca según la acción del músculo ciliar.</li><br /><li><strong>La túnica interna (retina).</strong> Es la membrana interna del ojo cuya porción nerviosa se compone de neuronas que sirven como receptores de luz (conos y bastones) y conductores de los impulsos nerviosos y señales bioquímicas que viajan hacia el cerebro para ser interpretadas como imágenes.<sup>1</sup></li></ol>";
    private String sec_2="La conjuntiva es una membrana delgada que recubre la superficie interior de cada párpado y la parte anterior del globo ocular. Se divide en varias porciones diferentes:<br /><br /><ul><li><strong>La conjuntiva palpebral:</strong> que es gruesa y recubre los párpados.<sup>1</sup></li><br /><li><strong>La conjuntiva bulbar</strong> que se localiza en donde la conjuntiva se refleja sobre la superficie anterior del globo ocular. Esta porción es transparente y cubre la esclera (la porción blanca del ojo).<sup>1</sup> La conjuntiva termina donde empieza la córnea, la cual es el primer lente del ojo.</li><br /><li><strong>El saco conjuntival</strong>, que es el espacio que se forma debido a que la conjuntiva se continúa desde los párpados hacia la superficie anterior del ojo; permite los movimientos oculares y es donde suelen alojarse los cuerpos extraños que caen en el ojo.<sup>1</sup></li></ul>";
    private String sec_3="<ul><li>El <strong>aparato lacrimal </strong>se compone de la glándula lacrimal (que produce las lágrimas) y los conductos lacrimales por donde los fluidos drenan hacia el saco lacrimal y de allí a la cavidad nasal.<sup>1</sup></li><br /><li>La<strong> glándula lacrimal</strong> se encuentra localizada en la parte superior del ojo y \t\t\tsecreta el fluido lacrimal hacia el saco conjuntival del párpado superior; con cada parpadeo, este fluido se dispersa sobre la superficie del ojo.<sup>1</sup></li><br /><li>El <strong>fluido lacrimal</strong> es una secreción mucosa lubricante que contiene sustancias bactericidas.<sup>1</sup></li></ul>";
    private String sec_4="<ul><li>Las lágrimas forman una película lacrimal que es esencial para la visión, ya que mantiene la hidratación y lubricación de la superficie ocular y proporciona la principal superficie refractiva del sistema visual.<sup>2</sup></li><br /><li>La película lacrimal se compone de varias sustancias, que incluyen agua, agentes antibacteriales, lípidos, mucinas y citoquinas, e incluye varias capas:<sup>2</sup><br /><br /><ul><li> La capa mucosa mantiene las lágrimas en la superficie del ojo.</li><li> La capa acuosa contiene agua y proteínas que protegen el ojo.</li><li> La capa lipídica, que evita que las lágrimas se evaporen.</li></ul></li><br /> <li>Cuando alguno de los componentes del sistema lacrimal falla, la función de la película lacrimal se afecta, lo cual puede conducir a enfermedades como el “síndrome de ojo seco”.<sup>2</sup></li></ul>";
    private String sec_5="<ul><li>El ojo se divide internamente por el cristalino en dos cavidades: anterior y posterior. A su vez, la cavidad anterior se divide por el iris en una cámara anterior y una posterior.<sup>1</sup></li><br /><li>El humor acuoso es un fluido que ocupa la cámara anterior y posterior, y es producido por el cuerpo ciliar. La producción constante de este líquido mantiene la presión dentro del ojo (presión intraocular) en un determinado valor.<sup>1</sup></li><br /><li>La función del humor acuoso es la de llevar nutrientes al cristalino, córnea y otros tejidos, y recoger sus desechos metabólicos. También lleva neurotransmisores y estabiliza la estructura ocular, además de remover células inflamatorias y mediadores bioquímicos bajo ciertas condiciones patológicas.<sup>3</sup></li><br /><li>El humor acuoso es producido por el cuerpo ciliar, pasa desde la cámara posterior hacia la cámara anterior a través de la pupila, y es drenado hacia el torrente sanguíneo en el ángulo iridocorneal, a través de la malla trabecular hacia el canal de Schlemm (o seno venoso de la esclera).<sup>1,3</sup></li></ul>";
    private String sec_6="";
    private String sec_7="";
    private String sec_8_a="";
    private String sec_8_b="";
    private String sec_8_c="";
    private String sec_9="";
    private String sec_10="";
    private String sec_11="<ul><li>La conjuntivitis es la inflamación de la conjuntiva. Uno de los tipos de conjuntivitis más común es la conjuntivitis alérgica.</li><br /><li>n alérgeno es una sustancia capaz de producir alergia (como por ejemplo el polen o el moho).</li><br /><li>a inflamación producida por la alergia es el resultado de una interacción compleja entre elementos celulares como macrófagos, linfocitos y mastocitos.<sup>10</sup></li><br /><li>as células inflamatorias activadas producen varias sustancias pro-inflamatorias, como la histamina.<sup>10</sup></li></ul>";
    private String sec_12="Algunos de los principales aeroalérgenos para conjuntivitis alérgica incluyen:<br /><br /><ul><li>Bacterias (células, fragmentos celulares o sus metabolitos)<sup>11</sup></li><br /><li> Hongos (esporas, fragmentos y metabolitos) <sup>11</sup></li><br /><li> Algas y protozoarios<sup>11</sup></li><br /><li> Helechos y musgos (esporas) <sup>11</sup></li>  <br /><li> Plantas (polen, partículas celulares) <sup>11</sup></li><br /><li> Artrópodos (heces, saliva y partes del cuerpo) <sup>11</sup></li><br /><li> Pájaros (heces y partes de su piel) <sup>11</sup></li><br /><li> Mamíferos (caspa, saliva, orina) <sup>11</sup></li><br /></ul>";
    private String sec_13_a="";
    private String sec_13_b="";
    private String sec_14="";
    private String sec_15="";
    private String sec_16="";
    private String sec_17="<ol><li>Van de Graaff K. Van de Graaff Human Anatomy, 6a ed. McGraw Hill Higher Education; 2001.</li><br /><li>Albersmeyer A, Gipson I. Dry eye: abnormalities of tear film mucins. In: Levin L, Albert D. Ocular Disease: Mechanisms and Management. Elsevier, 2010; pp: 138-145.</li><br /><li>Toris C. Aqueous Humor Dynamics and Intraocular Pressure Elevation. In: Shaarawy T, Sherwood M, Hitchings R, Crowston J. Glaucoma, 2nd. Ed. Elsevier, 2015; pp: 47-56.</li><br /><li>Dartt D. The lacrimal gland and dry-eye disease. In: Levin L, Albert D. Ocular Disease: Mechanisms and Management. Elsevier, 2010; pp: 105-113.</li><br /><li>Khouri A, Fechtner R. Primary Open-Angle Glaucoma. In: Shaarawy T, Sherwood M, Hitchings R, Crowston J. Glaucoma, 2nd. Ed. Elsevier, 2015; pp: 333-345.</li><br /><li>Foster P, Day A, Low S. Primary Angle-Closure Glaucoma. In: Shaarawy T, Sherwood M, Hitchings R, Crowston J. Glaucoma, 2nd. Ed. Elsevier, 2015; pp: 346-356.</li><br /><li>Crabb D. Visual Fields. In: Shaarawy T, Sherwood M, Hitchings R, Crowston J. Glaucoma, 2nd. Ed. Elsevier, 2015; pp: 109-124.</li><br /><li>Yücel Y, Gupta N. Central nervous system changes in glaucoma. In: Levin L, Albert D. Ocular Disease: Mechanisms and Management. Elsevier, 2010; pp: 200-206.</li><br /><li>Barney N, Cook E, Stahl J, Graziano F. Ocular allergy. In: Levin L, Albert D. Ocular Disease: Mechanisms and Management. Elsevier, 2010; pp: 98-104.</li>  <br /><li>Barnes P. Pathophysiology of Allergic Inflammation. In: Adkinson N, Bochner B, Burks A, Busse W, et al. Middleton's Allergy: Principles and Practice, 8th. Ed. Elsevier Saunders, 2014; pp: 327-342.</li><br /><li>Weber R. Aerobiology of Outdoor Allergens. In: Adkinson N, Bochner B, Burks A, Busse W, et al. Middleton's Allergy: Principles and Practice, 8th. Ed. Elsevier Saunders, 2014; pp: 430-452.</li><br /><li>Yeung K. Bacterial Conjunctivitis. Medscape Reference, 2014. http://emedicine.medscape.com/article/1191730-overview#showall Acceso: 19 febrero 2015.</li><br />  <li>Foster C. Dry Eye Syndrome. Medscape Reference, 2014. http://emedicine.medscape.com/article/1210417-overview#showall Acceso: 6 abril, 2015.</li><br /></ol><br /><br />Aviso SSA: <br />Número de registro: <br />  Material exclusivo para profesionales de la salud <br />  ©(c) 2015 Allergan, Inc.<br />  ®(R) Marcas registradas de Allergan Inc. <br />  No. Zinc Maps MEX/0124/2015 <br />  Fecha de impresión/uso Junio/2015";
}
